### ISSUE TITLE
firefox improper css parsing

### ISSUE THREAD

**Issue by nicholsk18** [ainsleyclark/mesh-site#11]
using Firefox 72.0.2(64-bit) on windows, arch and android the site does not load correctly. 
I have attached an img as example.

Manually taking styles out https://meshcss.com/css/mesh.css and placing in to body <styles> fixes the issue

![meshcsserror](https://user-images.githubusercontent.com/38633639/73121216-9c88fe00-3f3d-11ea-85c9-60810cfb721b.png)

**Comment by ainsleyclark** [comment]
Fixed with PL
